name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout source code
      uses: actions/checkout@v3

    - name: ✅ Install and Build React frontend
      working-directory: ./foodhubadmin_frontend
      run: |
        npm install
        npm run build

    - name: ✅ Install and Build Spring Boot backend
      working-directory: ./foodhubAdmin_backend
      run: |
        chmod +x ./gradlew
        ./gradlew build -x test

    - name: ✅ Copy React build files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "./foodhubadmin_frontend/dist/**"
        target: "/home/ubuntu/build"
        strip_components: 2

    - name: ✅ Copy Backend JAR file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "./foodhubAdmin_backend/build/libs/foodhubAdmin_backend-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/"
        strip_components: 4

    - name: ✅ SSH into EC2 and restart backend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo systemctl restart foodhub